# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.provider "parallels" do |p|
    config.vm.box = "mpasternak/focal64-arm"
    p.update_guest_tools = true
    p.memory = 4096
    p.cpus = 4
  end

  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    apt-get update
    apt-get -y dist-upgrade
    apt-get install -y build-essential \
                       cmake \
                       vim-nox \
                       python3-dev \
                       mono-complete \
                       golang \
                       default-jdk \
                       npm \
                       ruby-dev \
                       php \
                       composer \
                       zlib1g-dev
  SHELL

  config.vm.synced_folder "~/Development", "/home/vagrant/Development"

  config.vm.provision "shell",
    path:       "../common/provision.ycm",
    privileged: false
end
