# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    apt-add-repository -y ppa:ondrej/php
    apt-get update
    apt-get -y dist-upgrade
    apt-get install -y build-essential \
                       cmake3 \
                       python3-dev \
                       mono-devel \
                       python-virtualenv \
                       git \
                       php7.2
  SHELL

  config.vm.provision "shell",
    path:       "../common/nvm_manual",
    privileged: false

  config.vm.provision "shell",
    path:       "../common/go_manual",
    privileged: false

  config.vm.provision "shell",
    path:       "../common/composer_manual",
    privileged: false

  config.vm.provision "shell",
    path:       "../common/rvm_deps.ubuntu",
    privileged: true

  config.vm.provision "shell",
    path:       "../common/rvm_manual",
    privileged: false

  config.vm.provision "shell",
    path:       "../common/vim",
    privileged: false

  config.vm.provision "shell",
    path:       "../common/provision.ycm",
    privileged: false
end
